FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "MasoksTech.API/MasoksTech.API.csproj"
RUN dotnet publish "MasoksTech.API/MasoksTech.API.csproj" -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "MasoksTech.API.dll"]
