// <auto-generated />
using System;
using MasoksTech.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MasoksTech.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("MasoksTech.Web.Models.InventarioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Periféricos",
                            ImagenUrl = "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=600&q=80",
                            Nombre = "Teclado Mecánico Masoks G1",
                            Precio = 320.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Periféricos",
                            ImagenUrl = "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&q=80",
                            Nombre = "Mouse Gamer Masoks Pro",
                            Precio = 180.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Audio",
                            ImagenUrl = "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&q=80",
                            Nombre = "Audífonos Masoks H2 Stereo",
                            Precio = 240.00m,
                            Stock = 12
                        });
                });

            modelBuilder.Entity("MasoksTech.Web.Models.UsuarioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Correo = "admin@masokstech.com",
                            Nombre = "Maks Admin",
                            Rol = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Correo = "juan.perez@masokstech.com",
                            Nombre = "Juan Pérez",
                            Rol = "Vendedor"
                        });
                });

            modelBuilder.Entity("MasoksTech.Web.Models.VentaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteCorreo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductoNombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
