name: Publicar en SmarterASP

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Compilar y Publicar Proyecto Web
      run: |
        dotnet restore MasoksTech.Web/MasoksTech.Web.csproj
        dotnet publish MasoksTech.Web/MasoksTech.Web.csproj -c Release -o ./publish --no-restore

    - name: Subir archivos por FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: win8041.site4now.net
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./publish/
        server-dir: /site1/
